version: '3'
services:
  vobysbot:
    image: vobysbot:arm64v8
    ports:
      - "80:8000"
    volumes:
      - ./config.json:/opt/bot/config.json
      - ./commands:/opt/bot/commands
      - ./scripts:/opt/bot/scripts
      - ./data:/opt/bot/data
